import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="my-10">
          <header>
            <nav>
              <a className="bg-cyan-500 m-4 p-1 border-r-2" href="/">
                Home
              </a>
              <a className="bg-cyan-500 mr-7 p-1 border-r-2" href="/dashboard">
                Dashboard
              </a>
              <a className="bg-cyan-500 mr-7 p-1 border-r-2" href="/blog">
                Blog
              </a>
              <span> ----Root Layout</span>
            </nav>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
